"""No repository path may reach the rendered manuscript, and the check can fail.

The manuscript carried twenty-three of them: `docs/22-formal-model.md` in §III,
`aep_core/core/intents.py` in a figure caption, eight `scripts/...` and
`experiments/...` paths in §IX, `.claude/agents/` and `prompts/` in the
generative-AI disclosure, and five more in the supplementary. A submitted paper
does not cite the files of the repository that produced it, and under
double-anonymous review a path naming a personal layout is an anonymity risk.

`scripts/check_no_repo_paths.py` reads the PDFs rather than the LaTeX, because
a `\texttt{}` reaches the page from a caption, a footnote, a table cell or a
generated file by four different routes and only the extracted text sees all of
them. Two of the twenty-three were in `paper/generated/table-outcomes.tex`,
which no one edits by hand.

**The known-positives are the point.** Every way the check can fire is
exercised against text that must make it fire, and every exemption is exercised
against text that must not.
"""
from __future__ import annotations

import shutil

import pytest

from scripts.check_no_repo_paths import BUILDS, PAPER, check, findings

pytestmark = pytest.mark.skipif(
    shutil.which("pdftotext") is None,
    reason="pdftotext (poppler-utils) is not installed",
)


# -- the committed state ----------------------------------------------------

@pytest.mark.parametrize("name", BUILDS)
def test_no_build_carries_a_repository_path(name):
    pdf = PAPER / name
    if not pdf.is_file():
        pytest.skip(f"{name} has not been built")
    assert check(pdf) == []


def test_the_manuscript_still_cites_vendor_documentation_urls():
    """The exemption must not have been bought by deleting the citations."""
    from scripts.check_no_repo_paths import extract_text

    pdf = PAPER / "main.pdf"
    if not pdf.is_file():
        pytest.skip("main.pdf has not been built")
    text = extract_text(pdf)
    assert "redis.io/docs/latest" in text.replace("\n", "")
    assert "cadenceworkflow.io/docs" in text.replace("\n", "")


# -- known-positives: each pattern, made to fire ---------------------------

@pytest.mark.parametrize("line,expected", [
    ("This section condenses docs/22-formal-model.md in", "docs/22-formal-model.md"),
    ("generated by scripts/paper_tables.py from", "scripts/paper_tables.py"),
    ("so experiments/flakey_write_loss.py is not", "experiments/flakey_write_loss.py"),
    ("the transition table in aep_core/core/intents.py.", "aep_core/core/intents.py"),
    ("in its .claude/agents/ definitions, which", ".claude/agents/"),
    ("are committed in prompts/ in that repository", "prompts/"),
    ("ship in the raw archive under results/voided/ with", "results/voided/"),
    ("in analysis/coverage.json in the artifact.", "analysis/coverage.json"),
    ("cell is in experiments/results/matrix/MANIFEST.md and", "experiments/results/matrix/MANIFEST.md"),
])
def test_known_positive_a_repository_path_is_caught(line, expected):
    hits = findings(line)
    assert hits, f"{line!r} passed the check"
    assert any(h[2] == expected for h in hits), hits


@pytest.mark.parametrize("line,expected", [
    ("The environment is locked (uv.lock), the", "uv.lock"),
    ("bootstrap intervals in per-cell-metrics.csv are wider", "per-cell-metrics.csv"),
    ("Source: redis-kill-ablation.csv, regime", "redis-kill-ablation.csv"),
    ("enumerated in ARTIFACT.md: per-cell and", "ARTIFACT.md"),
    ("a SHA-256 in its own MANIFEST.sha256, and", "MANIFEST.sha256"),
    ("keyed in the tracked MANIFEST.csv. The raw", "MANIFEST.csv"),
    ("and analyze.py prints the warning itself.", "analyze.py"),
])
def test_known_positive_a_bare_source_filename_is_caught(line, expected):
    hits = findings(line)
    assert hits, f"{line!r} passed the check"
    assert any(h[2] == expected for h in hits), hits


def test_known_positive_every_pattern_has_at_least_one_firing_case():
    """If a pattern stops matching anything, it has stopped checking."""
    corpus = "\n".join([
        "condenses docs/22-formal-model.md in the artifact",
        "locked (uv.lock), the Redis image",
        "in its own MANIFEST.sha256, and that",
        "enumerated in ARTIFACT.md: per-cell",
    ])
    kinds = {kind for _, kind, _, _ in findings(corpus)}
    assert kinds == {"repository path", "source filename",
                     "manifest filename", "artifact doc"}, kinds


def test_known_positive_a_generated_table_caption_is_caught():
    """Two of the original twenty-three were in paper/generated/."""
    caption = ("and the per-crash-point rates behind every cell here are in "
               "per-cell-metrics.csv. Source: per-cell-metrics.csv, crashed "
               "regime only.")
    hits = findings(caption)
    assert len(hits) == 2, hits


# -- the exemptions, exercised against text that must NOT fire -------------

@pytest.mark.parametrize("line", [
    'Redis, "Redis persistence," https://redis.io/docs/latest/operate/',
    '[10] Redis, "WAITAOF," https://redis.io/docs/latest/commands/',
    '[14] Redis, "Distributed locks with Redis," https://redis.io/docs/',
    "Uber Technologies, https://cadenceworkflow.io/docs/concepts/workflows,",
    "available at https://github.com/example/repo/scripts/thing.py",
    "deposited at https://doi.org/10.5281/zenodo.22766567",
])
def test_vendor_and_archive_urls_are_not_repository_paths(line):
    assert findings(line) == [], findings(line)


@pytest.mark.parametrize("line", [
    "AEP-full/B3 record zero undetected duplicates",
    "the auth/pos-only/none capability classes",
    "a read/write split across the lease",
    "the fsync(2) and not the write(2)",
    "an append-only file with appendfsync everysec",
    "B4b durable, max attempts = 1",
    "input/output tokens billed at the published rate",
])
def test_ordinary_prose_with_a_slash_or_a_dot_is_not_a_path(line):
    assert findings(line) == [], findings(line)


def test_a_wrapped_vendor_url_does_not_fire_on_its_continuation():
    """URLs break across lines in two-column layout, and the tail looks bare."""
    wrapped = (
        'Redis, "Redis persistence," https://redis.io/docs/latest/operate/\n'
        "oss_and_stack/management/persistence/, 2026, accessed 2026-08-07."
    )
    assert findings(wrapped) == [], findings(wrapped)
