"""Put the two fsync policies side by side, and emit the paper's fragment.

The comparison is only meaningful because the two cells are otherwise
identical: same system (AEP-full), same endpoint, same crash-free regime, same
matrix seed and therefore the same per-run seeds, same host, same provider
delay. The only difference is ``appendfsync``.

Both sides are subject to the E5 timing gate: a run contributes a duration only
if the host was declared non-suspending before the run *and* no
wall-versus-monotonic divergence was observed in it. The gate is applied by
``analyze.py``; this script reads the gated aggregates and prints the
denominator it used, so a thin cell cannot pass as a solid one.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

#: The provider's configured delay. One round trip is the floor under which no
#: protocol can go, so the interesting quantity is the increment over it.
PROVIDER_DELAY_MS = 2000.0


def read_system(path: Path, system: str) -> dict[str, str] | None:
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            if row["system"] == system:
                return row
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--always", type=Path, required=True)
    parser.add_argument("--everysec", type=Path, required=True)
    parser.add_argument("--system", default="AEP_FULL")
    parser.add_argument(
        "--emit",
        type=Path,
        default=None,
        help="write the LaTeX fragment for paper/generated/fsync-comparison.tex",
    )
    arguments = parser.parse_args()

    always = read_system(arguments.always, arguments.system)
    everysec = read_system(arguments.everysec, arguments.system)
    if always is None or everysec is None:
        raise SystemExit(
            f"{arguments.system} missing from one of the two files "
            f"(always={always is not None}, everysec={everysec is not None})"
        )

    rows = []
    for label, row in (("everysec", everysec), ("always", always)):
        crash_free = int(row["overhead_runs_crash_free"] or 0)
        if not crash_free:
            raise SystemExit(
                f"the {label} cell has no crash-free run with usable timing; "
                "there is nothing to compare. Check the E5 gate output."
            )
        median = float(row["step_latency_ms_median"])
        rows.append(
            {
                "policy": label,
                "runs": crash_free,
                "executions": int(row["step_latency_ms_count"]),
                "median": median,
                "p95": float(row["step_latency_ms_p95"]),
                "over_floor": median - PROVIDER_DELAY_MS,
            }
        )

    width = 78
    print("=" * width)
    print(f"Barrier cost as a function of durability policy -- {arguments.system}")
    print("=" * width)
    print(
        f"{'appendfsync':<14}{'runs':>6}{'exec':>7}"
        f"{'median ms':>12}{'p95 ms':>11}{'over 2000ms floor':>20}"
    )
    print("-" * width)
    for row in rows:
        print(
            f"{row['policy']:<14}{row['runs']:>6}{row['executions']:>7}"
            f"{row['median']:>12.1f}{row['p95']:>11.1f}"
            f"{row['over_floor']:>20.1f}"
        )
    print("-" * width)

    delta = rows[0]["over_floor"] - rows[1]["over_floor"]
    print(
        f"\nTwo WAITAOF barriers cost {rows[0]['over_floor']:.1f} ms under "
        f"everysec and {rows[1]['over_floor']:.1f} ms under always."
    )
    print(f"Difference: {delta:.1f} ms.")
    print(
        "\nThe everysec figure is the one a reader would otherwise take as "
        "'AEP's overhead'.\nIt is the cost of waiting for a scheduled fsync "
        "that is up to one second away,\nnot the cost of the protocol. The "
        "protocol minus the barrier costs 28 ms\n(B3 versus B0, same cell "
        "family)."
    )

    if arguments.emit:
        fragment = [
            "% GENERATED by scripts/fsync_compare.py -- do not edit.",
            f"% Sources: {arguments.always} (always),",
            f"%          {arguments.everysec} (everysec).",
            "% Both are step_latency_ms_median over crash-free, E5-gated runs",
            f"% for system={arguments.system}. Provider floor "
            f"{PROVIDER_DELAY_MS:.0f} ms subtracted for the third column.",
            r"\begin{table}[t]",
            r"\centering",
            r"\caption{The barrier's cost is a property of the durability "
            r"configuration. Identical cell --- same system, endpoint, "
            r"regime, seeds and host --- run against two "
            r"\texttt{appendfsync} settings. Crash-free runs only, E5-gated.}",
            r"\label{tab:fsync}",
            r"\small",
            r"\begin{tabular}{@{}lrrrr@{}}",
            r"\toprule",
            r"\texttt{appendfsync} & runs & exec. & median (ms) & "
            r"over floor (ms)\\",
            r"\midrule",
        ]
        def tex(value: float) -> str:
            # The separator belongs to the number, not to the assembled row.
            return f"{value:,.1f}".replace(",", r"\,")

        for row in rows:
            fragment.append(
                f"\\texttt{{{row['policy']}}} & {row['runs']} & "
                f"{row['executions']} & {tex(row['median'])} & "
                f"{tex(row['over_floor'])}\\\\"
            )
        fragment.append(r"\midrule")
        fragment.append(
            r"\multicolumn{5}{@{}p{0.94\columnwidth}@{}}{\footnotesize "
            r"The two rows differ in one setting. Everything else --- system, "
            r"endpoint, crash-free regime, seeds, host, provider delay --- is "
            r"identical, so the difference of "
            f"{tex(abs(delta))}"
            r"\,ms is the price of the durability policy, not of the "
            r"protocol.}\\"
        )
        fragment += [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
        arguments.emit.parent.mkdir(parents=True, exist_ok=True)
        arguments.emit.write_text("\n".join(fragment) + "\n", encoding="utf-8")
        print(f"\nwrote {arguments.emit}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
