"""Emit the paper's state-machine figure from the code's transition table.

`PAPER_ROADMAP.md` §5's Phase 4 prompt: *"Generate the protocol state-machine
figure with TikZ from the transition table in aep_core/core/intents.py."*

The point of generating rather than drawing is drift. A hand-drawn figure is a
claim about the protocol that nothing checks, and this repository's audit
history is largely a history of documents that claimed properties the code did
not have. Here the edge set is imported, so a transition added to or removed
from ``LEGAL_INTENT_TRANSITIONS`` changes the figure or fails the build --
``scripts/check_paper_numbers.py`` re-runs this and diffs the result.

Layout is fixed by hand (positions, bend directions); only the *edges* come
from the code. If an edge appears that has no declared position, this script
exits non-zero rather than dropping it silently.

Usage:
    python scripts/gen_state_machine.py > paper/figures/state-machine.tex
    python scripts/gen_state_machine.py --check paper/figures/state-machine.tex
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from aep_core.core.intents import (  # noqa: E402
    LEGAL_INTENT_TRANSITIONS,
    NONE_STATE,
    IntentStatus,
)

#: Node identifier and printed label per status. Short identifiers keep the
#: generated TikZ readable when a reviewer opens it.
NODES: dict[str, tuple[str, str]] = {
    NONE_STATE: ("none", r"\textsc{none}"),
    IntentStatus.ABOUT_TO_FIRE.value: ("atf", r"\textsc{about-to-fire}"),
    IntentStatus.FIRED_UNCONFIRMED.value: ("fu", r"\textsc{fired-unconfirmed}"),
    IntentStatus.FIRED_CONFIRMED.value: ("fc", r"\textsc{fired-confirmed}"),
    IntentStatus.FAILED_CONFIRMED.value: ("flc", r"\textsc{failed-confirmed}"),
    IntentStatus.PERMANENTLY_AMBIGUOUS.value: ("pa", r"\textsc{ambiguous}"),
}

#: ``at`` positions on a coordinate grid, in TikZ units.
POSITIONS: dict[str, tuple[float, float]] = {
    "none": (0.0, 0.0),
    "atf": (0.0, -1.5),
    "fu": (0.0, -3.2),
    "fc": (-2.5, -4.9),
    "flc": (2.5, -4.9),
    "pa": (0.0, -4.9),
}

#: Per-edge drawing options and label. ``operator`` marks the two edges that
#: only a human can take; they are drawn dashed so the figure shows at a glance
#: that nothing automated leaves the ambiguous state.
EDGES: dict[tuple[str, str], tuple[str, str, bool]] = {
    # (from, to): (tikz options, label, is_operator_edge)
    (NONE_STATE, IntentStatus.ABOUT_TO_FIRE.value): (
        "", r"\scriptsize CAS $+$ barrier", False,
    ),
    (IntentStatus.ABOUT_TO_FIRE.value, IntentStatus.FIRED_CONFIRMED.value): (
        "bend right=52", r"\scriptsize declared success", False,
    ),
    (IntentStatus.ABOUT_TO_FIRE.value, IntentStatus.FAILED_CONFIRMED.value): (
        "bend left=52", r"\scriptsize declared failure", False,
    ),
    (IntentStatus.ABOUT_TO_FIRE.value, IntentStatus.FIRED_UNCONFIRMED.value): (
        "", r"\scriptsize anything else", False,
    ),
    (
        IntentStatus.FIRED_UNCONFIRMED.value,
        IntentStatus.FIRED_UNCONFIRMED.value,
    ): (
        "loop right", r"\scriptsize unknown; budget left", False,
    ),
    (IntentStatus.FIRED_UNCONFIRMED.value, IntentStatus.FIRED_CONFIRMED.value): (
        "", r"\scriptsize read-back applied", False,
    ),
    (IntentStatus.FIRED_UNCONFIRMED.value, IntentStatus.FAILED_CONFIRMED.value): (
        "", r"\scriptsize authoritative absence", False,
    ),
    (
        IntentStatus.FIRED_UNCONFIRMED.value,
        IntentStatus.PERMANENTLY_AMBIGUOUS.value,
    ): (
        "", r"\scriptsize budget spent", False,
    ),
    (
        IntentStatus.PERMANENTLY_AMBIGUOUS.value,
        IntentStatus.FIRED_CONFIRMED.value,
    ): (
        "dashed,bend left=18", "", True,
    ),
    (
        IntentStatus.PERMANENTLY_AMBIGUOUS.value,
        IntentStatus.FAILED_CONFIRMED.value,
    ): (
        "dashed,bend right=18", "", True,
    ),
}


def render() -> str:
    missing = sorted(set(LEGAL_INTENT_TRANSITIONS) - set(EDGES))
    extra = sorted(set(EDGES) - set(LEGAL_INTENT_TRANSITIONS))
    if missing or extra:
        raise SystemExit(
            "the transition table and the figure's edge list disagree.\n"
            f"  in the code but not drawn: {missing}\n"
            f"  drawn but not in the code: {extra}\n"
            "Edit EDGES in scripts/gen_state_machine.py -- do not edit the "
            "generated .tex."
        )

    out: list[str] = []
    out.append("% GENERATED by scripts/gen_state_machine.py -- do not edit.")
    out.append("% Edge set imported from aep_core.core.intents")
    out.append("% .LEGAL_INTENT_TRANSITIONS, so this figure cannot drift from")
    out.append("% the transition table the Lua script enforces.")
    out.append(f"% {len(LEGAL_INTENT_TRANSITIONS)} edges, 6 states.")
    out.append(r"\begin{tikzpicture}[")
    out.append(r"    node distance=6mm,")
    out.append(r"    every node/.style={font=\footnotesize},")
    out.append(
        r"    state/.style={draw,rounded corners=2pt,inner sep=3pt,"
        r"align=center,fill=black!3},"
    )
    out.append(
        r"    terminal/.style={state,fill=black!8,very thick},"
    )
    out.append(r"    to/.style={-{Stealth[length=4pt]},shorten >=1pt},")
    out.append(r"  ]")

    terminal = {
        IntentStatus.FIRED_CONFIRMED.value,
        IntentStatus.FAILED_CONFIRMED.value,
    }
    for status, (ident, label) in NODES.items():
        x, y = POSITIONS[ident]
        style = "terminal" if status in terminal else "state"
        out.append(f"  \\node[{style}] ({ident}) at ({x},{y}) {{{label}}};")

    out.append("")
    for (source, target), (options, label, _operator) in EDGES.items():
        src = NODES[source][0]
        dst = NODES[target][0]
        opt = f"to,{options}" if options else "to"
        text = f" node[midway,sloped,above] {{{label}}}" if label else ""
        out.append(f"  \\draw[{opt}] ({src}) edge{text} ({dst});")

    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        metavar="PATH",
        help="compare against an existing file instead of writing to stdout",
    )
    arguments = parser.parse_args()
    rendered = render()

    if arguments.check:
        path = Path(arguments.check)
        if not path.is_file():
            print(f"MISSING: {path}", file=sys.stderr)
            return 1
        if path.read_text(encoding="utf-8") != rendered:
            print(
                f"STALE: {path} does not match the current transition table.\n"
                f"Regenerate: python scripts/gen_state_machine.py > {path}",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {path} matches aep_core.core.intents")
        return 0

    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
