"""Generate the manuscript's evaluation tables and numbers from the frozen CSVs.

Amendment F3: *"Every number in the paper carries a pointer (in a LaTeX
comment) to its CSV cell or raw report section."* The strongest form of that is
not to write the numbers by hand at all. Everything this script emits carries a
generated comment naming the file, the filter and the arithmetic that produced
it, so a reviewer can recompute any cell without reading Python.

Two rules are enforced here rather than remembered:

1. **``analysis/table-1.csv`` is never read.** Session 3B §F2 banned it: it
   pools fault regimes and response classes, so its rates are a property of the
   collected mix. The only rate source is ``per-cell-metrics.csv``.

2. **Regimes are never pooled.** Every rollup below filters to one regime and
   says which in the emitted comment. The default is the crashed regime, which
   is the one the duplicate/ambiguity claims are about; the crash-free ``p0``
   regime and the ``redis-kill-preack`` regime are reported separately because
   they are different experiments.

Usage:
    python scripts/paper_tables.py --analysis experiments/results/matrix/analysis \\
                                   --out paper/generated
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

#: The regime whose runs answer RQ1. A regime is a named fault condition, not
#: a matrix dimension; ``(session-3)`` is the one in which every execution is
#: killed at the cell's crash point.
CRASHED_REGIME = "(session-3)"
CRASH_FREE_REGIME = "p0"
REDIS_KILL_REGIME = "redis-kill-preack"

RESPONSE_ORDER = [
    "AUTHORITATIVE_READBACK",
    "POSITIVE_ONLY_READBACK",
    "NO_READBACK",
]
RESPONSE_SHORT = {
    "AUTHORITATIVE_READBACK": r"\textsc{auth}",
    "POSITIVE_ONLY_READBACK": r"\textsc{pos-only}",
    "NO_READBACK": r"\textsc{none}",
}
SYSTEM_ORDER = [
    "B0_NAIVE_RETRY",
    "B1_LEASE_ONLY",
    "B2_CAS_ONLY",
    "B4_DURABLE_WORKFLOW",
    "B4B_DURABLE_WORKFLOW_AT_MOST_ONCE",
    "B3_INTENT_NO_BARRIER",
    "AEP_FULL",
]
SYSTEM_LABEL = {
    "B0_NAIVE_RETRY": "B0 naive retry",
    "B1_LEASE_ONLY": "B1 lease-only",
    "B2_CAS_ONLY": "B2 CAS-only",
    "B3_INTENT_NO_BARRIER": "B3 intent, no barrier",
    "B4_DURABLE_WORKFLOW": r"B4 durable, $\infty$ attempts",
    "B4B_DURABLE_WORKFLOW_AT_MOST_ONCE": "B4b durable, 1 attempt",
    "AEP_FULL": r"\textbf{AEP-full}",
}
CRASH_POINT_LABEL = {
    "before_intent_write": r"\texttt{before\_intent\_write}",
    "after_intent_before_barrier": r"\texttt{after\_intent\_before\_barrier}",
    "after_barrier_before_dispatch": r"\texttt{after\_barrier\_before\_dispatch}",
    "mid_dispatch": r"\texttt{mid\_dispatch}",
    "after_response_before_resolution": r"\texttt{after\_response\_before\_res.}",
    "after_resolution_before_barrier": r"\texttt{after\_resolution\_before\_bar.}",
}
CRASH_POINT_ORDER = list(CRASH_POINT_LABEL)


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def totals(
    rows: Iterable[dict[str, str]], metric: str
) -> tuple[int, int]:
    successes = total = 0
    for row in rows:
        if row["metric"] != metric:
            continue
        successes += int(row["successes"])
        total += int(row["total"])
    return successes, total


def rate(successes: int, total: int) -> str:
    return f"{successes / total:.4f}" if total else "---"


def fraction(successes: int, total: int) -> str:
    return f"{successes}/{total}" if total else "---"


def emit_outcomes_table(rows: list[dict[str, str]], out: Path) -> None:
    """The anchor table: the trilemma, per system and endpoint capability."""
    crashed = [r for r in rows if r["regime"] == CRASHED_REGIME]
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in crashed:
        grouped[(row["system"], row["response_class"])].append(row)

    lines: list[str] = []
    lines.append(
        "% GENERATED by scripts/paper_tables.py -- do not edit by hand."
    )
    lines.append("% Source: analysis/per-cell-metrics.csv")
    lines.append(f"% Filter: regime == {CRASHED_REGIME!r} ONLY.")
    lines.append(
        "%   Every execution in these cells was killed at the cell's crash"
    )
    lines.append(
        "%   point. The crash-free (p0) and hard-Redis-kill (redis-kill-preack)"
    )
    lines.append(
        "%   regimes are DIFFERENT EXPERIMENTS and are reported separately;"
    )
    lines.append("%   pooling them is what got analysis/table-1.csv banned.")
    lines.append(
        "% Each cell = sum(successes)/sum(total) over the six crash points."
    )
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(
        r"\caption{The trilemma, measured. Every execution in every cell was "
        r"killed at one of the six crash points of \cref{tab:crashpoints}; "
        r"rates are over executions, pooled across crash points within one "
        r"endpoint capability. \textsc{auth}/\textsc{pos-only}/\textsc{none} "
        r"are the reconciliation capabilities of \cref{tab:capabilities}. "
        r"AEP-full is the only system with a nonzero declared-ambiguity "
        r"column, and the only one whose other two columns are zero "
        r"everywhere. Source: \texttt{per-cell-metrics.csv}, crashed regime "
        r"only.}"
    )
    lines.append(r"\label{tab:outcomes}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{@{}l" + "ccc" * 3 + r"@{}}")
    lines.append(r"\toprule")
    lines.append(
        r"& \multicolumn{3}{c}{undetected duplicate}"
        r"& \multicolumn{3}{c}{lost effect}"
        r"& \multicolumn{3}{c}{declared ambiguity}\\"
    )
    lines.append(r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}")
    header = " & ".join(RESPONSE_SHORT[c] for c in RESPONSE_ORDER)
    lines.append(f"system & {header} & {header} & {header}\\\\")
    lines.append(r"\midrule")

    for system in SYSTEM_ORDER:
        cells: list[str] = []
        present = False
        for metric in (
            "undetected_duplicate_rate",
            "lost_effect_rate",
            "known_ambiguity_rate",
        ):
            for response in RESPONSE_ORDER:
                successes, total = totals(
                    grouped.get((system, response), []), metric
                )
                if total:
                    present = True
                cells.append(rate(successes, total))
        if not present:
            continue
        lines.append(
            f"{SYSTEM_LABEL[system]} & " + " & ".join(cells) + r"\\"
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")

    # The denominators, as a comment, so no reader has to trust the rates.
    lines.append("")
    lines.append("% Denominators (executions) per (system, response class):")
    for system in SYSTEM_ORDER:
        for response in RESPONSE_ORDER:
            group = grouped.get((system, response), [])
            successes, total = totals(group, "undetected_duplicate_rate")
            if not total:
                continue
            # Runs are counted on ONE metric's rows. Summing over all of them
            # would multiply by the metric count, and recovery_success_rate
            # reports 0 runs for a system with no recovery service, which
            # would drag a min() to zero.
            runs = sum(
                int(r["runs"])
                for r in group
                if r["metric"] == "undetected_duplicate_rate"
            )
            points = sorted(
                {
                    r["crash_point"]
                    for r in group
                    if r["metric"] == "undetected_duplicate_rate"
                }
            )
            lines.append(
                f"%   {system:<34} {response:<24} "
                f"executions={total:<5} runs={runs:<4} "
                f"crash_points={len(points)}"
            )
    (out / "table-outcomes.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def emit_ambiguity_by_crashpoint(rows: list[dict[str, str]], out: Path) -> None:
    """Where AEP's declared ambiguity comes from, and where it does not."""
    crashed = [
        r
        for r in rows
        if r["regime"] == CRASHED_REGIME
        and r["system"] == "AEP_FULL"
        and r["metric"] == "known_ambiguity_rate"
    ]
    table: dict[tuple[str, str], tuple[int, int]] = {}
    for row in crashed:
        table[(row["crash_point"], row["response_class"])] = (
            int(row["successes"]),
            int(row["total"]),
        )

    lines: list[str] = []
    lines.append(
        "% GENERATED by scripts/paper_tables.py -- do not edit by hand."
    )
    lines.append(
        "% Source: analysis/per-cell-metrics.csv, "
        "metric=known_ambiguity_rate,"
    )
    lines.append(f"%         system=AEP_FULL, regime={CRASHED_REGIME!r}.")
    lines.append("% Cells are successes/total straight from the CSV row.")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(
        r"\caption{AEP-full's declared-ambiguity rate, by crash point and "
        r"endpoint capability. The rate is not a constant of the protocol: it "
        r"is zero where the crash precedes the intent write (nothing was "
        r"promised), zero throughout \textsc{auth} (absence is provable), and "
        r"highest exactly where no effect can exist but the endpoint cannot "
        r"say so. Undetected duplicates and lost effects are $0$ in every cell "
        r"of this table.}"
    )
    lines.append(r"\label{tab:ambiguity-by-crashpoint}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{@{}lccc@{}}")
    lines.append(r"\toprule")
    lines.append(
        "crash point & "
        + " & ".join(RESPONSE_SHORT[c] for c in RESPONSE_ORDER)
        + r"\\"
    )
    lines.append(r"\midrule")
    for point in CRASH_POINT_ORDER:
        cells = []
        for response in RESPONSE_ORDER:
            successes, total = table.get((point, response), (0, 0))
            cells.append(fraction(successes, total))
        if all(c == "---" for c in cells):
            continue
        lines.append(
            f"{CRASH_POINT_LABEL[point]} & " + " & ".join(cells) + r"\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    (out / "table-ambiguity-by-crashpoint.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def emit_numbers(
    per_cell: list[dict[str, str]],
    latency: list[dict[str, str]],
    kill: list[dict[str, str]],
    out: Path,
) -> None:
    """Headline scalars as macros, each with its provenance in a comment."""
    lines: list[str] = []
    lines.append("% GENERATED by scripts/paper_tables.py -- do not edit.")
    lines.append(
        "% Sources: analysis/per-cell-metrics.csv, "
        "analysis/latency-and-throughput.csv,"
    )
    lines.append("%          analysis/redis-kill-ablation.csv")
    lines.append(
        "% Each macro carries the file, filter and arithmetic behind it."
    )
    lines.append("")

    def macro(name: str, value: str, *provenance: str) -> None:
        for line in provenance:
            lines.append(f"% {line}")
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
        lines.append("")

    crashed = [r for r in per_cell if r["regime"] == CRASHED_REGIME]

    # --- RQ1: AEP's three columns, per capability -----------------------
    for response in RESPONSE_ORDER:
        subset = [
            r
            for r in crashed
            if r["system"] == "AEP_FULL" and r["response_class"] == response
        ]
        suffix = {
            "AUTHORITATIVE_READBACK": "Auth",
            "POSITIVE_ONLY_READBACK": "PosOnly",
            "NO_READBACK": "NoReadback",
        }[response]
        for metric, tag in (
            ("known_ambiguity_rate", "Amb"),
            ("undetected_duplicate_rate", "Dup"),
            ("lost_effect_rate", "Lost"),
        ):
            successes, total = totals(subset, metric)
            macro(
                f"Aep{tag}{suffix}",
                rate(successes, total),
                f"per-cell-metrics.csv | system=AEP_FULL "
                f"regime={CRASHED_REGIME} response_class={response}",
                f"metric={metric} | sum(successes)/sum(total) "
                f"= {successes}/{total}",
            )
            macro(
                f"Aep{tag}{suffix}N",
                str(total),
                f"denominator (executions) for \\Aep{tag}{suffix}",
            )

    # --- RQ3: latency, E5-gated only ------------------------------------
    for row in latency:
        crash_free = int(row["overhead_runs_crash_free"] or 0)
        if not crash_free:
            continue
        key = {
            "AEP_FULL": "Aep",
            "B0_NAIVE_RETRY": "Bzero",
            "B1_LEASE_ONLY": "Bone",
            "B2_CAS_ONLY": "Btwo",
            "B3_INTENT_NO_BARRIER": "Bthree",
            "B4_DURABLE_WORKFLOW": "Bfour",
            "B4B_DURABLE_WORKFLOW_AT_MOST_ONCE": "Bfourb",
        }.get(row["system"])
        if not key:
            continue
        median = float(row["step_latency_ms_median"])
        macro(
            f"{key}StepMedian",
            f"{median:,.1f}".replace(",", r"\,"),
            f"latency-and-throughput.csv | system={row['system']}",
            f"step_latency_ms_median over crash-free runs only "
            f"(overhead_runs_crash_free={crash_free})",
            "E5 gate: runs without a declared suspend-disabled host "
            "contribute NO timing",
        )

    # --- RQ2: the hard-Redis-kill ablation ------------------------------
    for row in kill:
        key = {
            "AEP_FULL": "Aep",
            "B3_INTENT_NO_BARRIER": "Bthree",
        }.get(row["system"])
        if not key:
            continue
        macro(
            f"{key}KillApplied",
            row["executions_with_an_applied_effect"],
            f"redis-kill-ablation.csv | regime={row['regime']} "
            f"system={row['system']} response_class={row['response_class']}",
            "executions_with_an_applied_effect",
        )
        macro(
            f"{key}KillRuns",
            row["runs"],
            f"redis-kill-ablation.csv | runs for {row['system']}",
        )
        macro(
            f"{key}KillCanary",
            f"{row['canary_survived']}/{int(row['canary_survived']) + int(row['canary_lost'])}",
            f"redis-kill-ablation.csv | canary_survived/(survived+lost) "
            f"for {row['system']}",
            "the un-acknowledged write made immediately before the hard kill",
        )

    (out / "numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--analysis", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    arguments = parser.parse_args()
    arguments.out.mkdir(parents=True, exist_ok=True)

    per_cell = read_rows(arguments.analysis / "per-cell-metrics.csv")
    if "regime" not in per_cell[0]:
        raise SystemExit(
            "per-cell-metrics.csv has no `regime` column. Re-run analyze.py: "
            "without it, a crash-free cell and a hard-Redis-kill cell can be "
            "averaged into one rate."
        )
    latency = read_rows(arguments.analysis / "latency-and-throughput.csv")
    kill = read_rows(arguments.analysis / "redis-kill-ablation.csv")

    emit_outcomes_table(per_cell, arguments.out)
    emit_ambiguity_by_crashpoint(per_cell, arguments.out)
    emit_numbers(per_cell, latency, kill, arguments.out)
    for name in sorted(p.name for p in arguments.out.glob("*.tex")):
        print(f"wrote {arguments.out / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
